# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for EESSI pilot repo
on: [push, pull_request]
jobs:
  pilot_repo:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        EESSI_VERSION:
        - "2020.12"
        EESSI_SOFTWARE_SUBDIR_OVERRIDE:
        - aarch64/generic
        - aarch64/a64fx
        - aarch64/generic
        - aarch64/graviton2
        - aarch64/thunderx2
        - ppc64le/power9le
        - x86_64/generic
        - x86_64/amd/zen2
        - x86_64/intel/haswell
        - x86_64/intel/skylake_avx512
        EESSI_DEMO:
        - Bioconductor
        - GROMACS
        - OpenFOAM
        - TensorFlow
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@v2

        - name: Install QEMU
          if: env.EESSI_ARCH != 'x86_64'
          run: |
              sudo apt-get update
              sudo apt-get install qemu-user

        - name: Mount EESSI CernVM-FS pilot repository
          uses: cvmfs-contrib/github-action-cvmfs@main
          with:
              cvmfs_config_package: https://github.com/EESSI/filesystem-layer/releases/download/v0.2.3/cvmfs-config-eessi_0.2.3_all.deb
              cvmfs_http_proxy: DIRECT
              cvmfs_repositories: pilot.eessi-hpc.org

        - name: Run demo
          env:
              EESSI_SOFTWARE_SUBDIR_OVERRIDE: ${{matrix.EESSI_SOFTWARE_SUBDIR_OVERRIDE}}
          run: |
              source /cvmfs/pilot.eessi-hpc.org/${{matrix.EESSI_VERSION}}/init/bash

              cd ${{matrix.EESSI_DEMO}}
              pwd
              ./run.sh
